### ISSUE TITLE
Update minimum Rust version to match `notify` upstream

### ISSUE THREAD

**Issue by ErichDonGubler** [francesca64/hotwatch#1]
Upstream `notify`'s [README](https://github.com/passcod/notify) states, as of [v4.0.7](https://github.com/passcod/notify/tree/v4.0.7):

> Earliest supported Rust version: **1.26.1**

But `hotwatch`'s README states:

> At least Rust 1.24 is required, ....

This should be updated to indicate upstream's minimum requirements of 1.26.1, since 4.0.7 is technically semver-compatible with this crate!

**Comment by francesca64** [comment]
Sorry for the delay!

I'd prefer to just only target the latest stable Rust, unless you have any objections.

**Comment by ErichDonGubler** [comment]
That's not a bad option either! :) I have no objections, provided that you update the docs. Bonus: if you say latest stable Rust, then you might not have to update it again. :P

**Comment by francesca64** [comment]
Fixed in 2dfda1c6fa1d8238bf70727128cde05011a6fbe6 and released as [0.4.0](https://crates.io/crates/hotwatch/0.4.0)

(Sorry for the delay! I've been busy with a new job.)
