### ISSUE TITLE
~3 second delay from file change to change notification

### ISSUE THREAD

**Issue by eliasjonsson023** [francesca64/hotwatch#14]
Is there a way of improving the ~3 second latency from file change to change notification?

**Comment by francesca64** [comment]
Are you using `Hotwatch::new`, or [`Hotwatch::new_with_custom_delay`](https://docs.rs/hotwatch/latest/hotwatch/struct.Hotwatch.html#method.new_with_custom_delay)? The latter allows you to specify any delay you'd like.

The documentation for `new` could certainly be more clear about this behavior, as could the API itself; it might not be the most helpful default.

**Comment by eliasjonsson023** [comment]
Yes, it works. With Hotwatch::new_with_custom_delay it is possible to watch file changes at any latency.
