### ISSUE TITLE
Event::Modify raised twice on Mac M1

### ISSUE THREAD

**Issue by Alphapage** [francesca64/hotwatch#15]
Hello,

I try the example without success: the event is always raised twice when I save the file.

It was working at the beginning, but now it seems broken.
I restarted my Mac without success.

Do you have the same behaviour ?

Thank you in advance for your help.

**Comment by francesca64** [comment]
Thank you for reporting this! Does #15 fix this for you?

**Comment by Alphapage** [comment]
No: I get 2 events:
- notify::event::RenameMode::Any
- notify::event::MetadataKind::Extended
but no Modify::Data

**Comment by Alphapage** [comment]
Well, it seems RenameMode::Any is raised to signal a modification from the file.
But then Mac OS raises a Metadata event because it is updating the modification time I think.
So, I inserted those lines to bypass this problem:
```rust
if let EventKind::Modify(ModifyKind::Metadata(_)) =
                            event.kind
                        {
                            return;
                        }
```
because I don't need any metadata event for now.
