### ISSUE TITLE
`Hotwatch::watch` suddenly always returns `No space left on device (os error 28)`

### ISSUE THREAD

**Issue by Boscop** [francesca64/hotwatch#6]
I get this on linux:
```
Error: watch

Caused by:
    No space left on device (os error 28)
```
With this code:
```rust
let mut hotwatch = Hotwatch::new_with_custom_delay(Duration::from_millis(50)).context("Hotwatch")?;
hotwatch.watch(folder_path, move |event: Event| {
    // ...
}).context("watch")?;
```
It was working a few days ago. Now it **always** fails. Any idea why? (I just updated to `hotwatch v0.4.5` but same error.)
There is definitely much space left on the disk.
(And `Hotwatch` shouldn't even need space on the disk since it doesn't create any files.)

**Comment by Boscop** [comment]
Nvm, the partition was actually full (only other partitions had space left) -.-

**Comment by Boscop** [comment]
@francesca64 Actually the reason was not that the partition was full because the error still occurred after I made space. The reason why hotwatch returned failed was that there were no more watcher handles available on the system (`fs.inotify.max_user_watches`). (It worked again after reboot.) 
Could you maybe improve the error message for that case? :)

**Comment by francesca64** [comment]
This is actually an issue 3 levels upstream.. notify-rs/notify#266

notify intends to fix it on their end, but it doesn't look like anyone's gotten around to that yet.
